import Head from "./common-parts/Head";
import Bottom from "./common-parts/Bottom";
import { FaFacebook, FaYoutube, FaLinkedin } from "react-icons/fa";
import "./globals.css";

export const metadata = {
  title: "Deshcareer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-yellow-50 h-min-screen w-screen ">
        <Head />
        {children}
        <Bottom />
      </body>
    </html>
  );
}
